<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\PaulsTransitData\PaulsTransitData.csproj" />
      <ProjectReference Include="..\Platform22.Orleans\Platform22.Orleans.csproj" />
    </ItemGroup>

    <ItemGroup>
      <InternalsVisibleTo Include="Platform22.Tests" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FxSsh" Version="1.4.0" />
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
      <PackageReference Include="Microsoft.Orleans.Client" Version="10.2.2" />
      <PackageReference Include="Microsoft.Orleans.Clustering.Redis" Version="10.2.2" />
      <PackageReference Include="Microsoft.Orleans.Server" Version="10.2.2" />
      <PackageReference Include="Terminal.Gui" Version="1.17.1" />
    </ItemGroup>

</Project>
