apiVersion: apps/v1
kind: Deployment
metadata:
  name: orleans-host
spec:
  replicas: 2
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: tmp
          emptyDir: {}
      containers:
        - name: orleans-host
          env:
            - name: ORLEANS_CLUSTERING_MODE
              value: kubernetes
          ports:
            - name: gateway
              containerPort: 30000
              protocol: TCP
            - name: silo
              containerPort: 11111
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: gateway
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: gateway
            periodSeconds: 20
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
